
export const localization  = {
  locale: 'kk-KZ',
  __experimental_commerce: {
    billedAnnually: undefined,
    free: undefined,
    getStarted: undefined,
    manageSubscription: undefined,
    month: undefined,
    switchPlan: undefined,
  },
  backButton: 'Артқа',
  badge__currentPlan: undefined,
  badge__default: 'Әдепкі',
  badge__otherImpersonatorDevice: 'Басқа құрылғы',
  badge__primary: 'Негізгі',
  badge__requiresAction: 'Әрекет қажет',
  badge__thisDevice: 'Бұл құрылғы',
  badge__unverified: 'Расталмаған',
  badge__userDevice: 'Пайдаланушы құрылғысы',
  badge__you: 'Сіз',
  createOrganization: {
    formButtonSubmit: 'Ұйым құру',
    invitePage: {
      formButtonReset: 'Өткізіп жіберу',
    },
    title: 'Ұйым құру',
  },
  dates: {
    lastDay: "Кеше {{ date | timeString('kk-KZ') }}",
    next6Days: "{{ date | weekday('kk-KZ','long') }} {{ date | timeString('kk-KZ') }}",
    nextDay: "Ертең {{ date | timeString('kk-KZ') }}",
    numeric: "{{ date | numeric('kk-KZ') }}",
    previous6Days: "Өткен {{ date | weekday('kk-KZ','long') }} {{ date | timeString('kk-KZ') }}",
    sameDay: "Бүгін {{ date | timeString('kk-KZ') }}",
  },
  dividerText: 'немесе',
  footerActionLink__useAnotherMethod: 'Басқа әдісті қолдану',
  footerPageLink__help: 'Көмек',
  footerPageLink__privacy: 'Құпиялық',
  footerPageLink__terms: 'Шарттар',
  formButtonPrimary: 'Жалғастыру',
  formButtonPrimary__verify: 'Растау',
  formFieldAction__forgotPassword: 'Құпия сөзді ұмыттыңыз ба?',
  formFieldError__matchingPasswords: 'Құпия сөздер сәйкес келеді.',
  formFieldError__notMatchingPasswords: 'Құпия сөздер сәйкес келмейді.',
  formFieldError__verificationLinkExpired:
    'Растау сілтемесінің мерзімі аяқталды. Жаңа сілтеме сұраңыз.',
  formFieldHintText__optional: 'Қосымша',
  formFieldHintText__slug:
    'Slug - бұл адам оқи алатын бірегей идентификатор. Ол әдетте URL мекенжайларында қолданылады.',
  formFieldInputPlaceholder__backupCode: undefined,
  formFieldInputPlaceholder__confirmDeletionUserAccount: 'Тіркелгіні жою',
  formFieldInputPlaceholder__emailAddress: undefined,
  formFieldInputPlaceholder__emailAddress_username: undefined,
  formFieldInputPlaceholder__emailAddresses:
    'Бір немесе бірнеше электрондық пошта мекенжайларын енгізіңіз немесе қойыңыз, оларды бос орындар немесе үтірлер арқылы бөліңіз',
  formFieldInputPlaceholder__firstName: undefined,
  formFieldInputPlaceholder__lastName: undefined,
  formFieldInputPlaceholder__organizationDomain: undefined,
  formFieldInputPlaceholder__organizationDomainEmailAddress: undefined,
  formFieldInputPlaceholder__organizationName: undefined,
  formFieldInputPlaceholder__organizationSlug: 'my-org',
  formFieldInputPlaceholder__password: undefined,
  formFieldInputPlaceholder__phoneNumber: undefined,
  formFieldInputPlaceholder__username: undefined,
  formFieldLabel__automaticInvitations: 'Бұл домен үшін автоматты шақыруларды қосу',
  formFieldLabel__backupCode: 'Сақтық коды',
  formFieldLabel__confirmDeletion: 'Растау',
  formFieldLabel__confirmPassword: 'Құпия сөзді растау',
  formFieldLabel__currentPassword: 'Ағымдағы құпия сөз',
  formFieldLabel__emailAddress: 'Электрондық пошта',
  formFieldLabel__emailAddress_username: 'Электрондық пошта немесе пайдаланушы аты',
  formFieldLabel__emailAddresses: 'Электрондық пошта мекенжайлары',
  formFieldLabel__firstName: 'Аты',
  formFieldLabel__lastName: 'Тегі',
  formFieldLabel__newPassword: 'Жаңа құпия сөз',
  formFieldLabel__organizationDomain: 'Домен',
  formFieldLabel__organizationDomainDeletePending: 'Күтудегі шақырулар мен ұсыныстарды жою',
  formFieldLabel__organizationDomainEmailAddress: 'Электрондық пошта мекенжайын растау',
  formFieldLabel__organizationDomainEmailAddressDescription:
    'Доменді растау үшін осы домендегі электрондық пошта мекенжайын енгізіп, код алыңыз.',
  formFieldLabel__organizationName: 'Ұйым атауы',
  formFieldLabel__organizationSlug: 'Slug',
  formFieldLabel__passkeyName: 'Кіру кілті атауы',
  formFieldLabel__password: 'Құпия сөз',
  formFieldLabel__phoneNumber: 'Телефон нөмірі',
  formFieldLabel__role: 'Рөл',
  formFieldLabel__signOutOfOtherSessions: 'Басқа құрылғылардан шығу',
  formFieldLabel__username: 'Пайдаланушы аты',
  impersonationFab: {
    action__signOut: 'Шығу',
    title: 'Сіз {{identifier}} ретінде кірдіңіз',
  },
  maintenanceMode:
    'Қазір техникалық қызмет көрсету жұмыстары жүргізілуде, бірақ бұл бірнеше минуттан аспайды.',
  membershipRole__admin: 'Әкімші',
  membershipRole__basicMember: 'Мүше',
  membershipRole__guestMember: 'Қонақ',
  organizationList: {
    action__createOrganization: 'Ұйым құру',
    action__invitationAccept: 'Қосылу',
    action__suggestionsAccept: 'Қосылу сұрауы',
    createOrganization: 'Ұйым Құру',
    invitationAcceptedLabel: 'Қосылды',
    subtitle: '{{applicationName}} қолданбасын жалғастыру үшін',
    suggestionsAcceptedLabel: 'Бекіту күтілуде',
    title: 'Тіркелгіні таңдау',
    titleWithoutPersonal: 'Ұйымды таңдау',
  },
  organizationProfile: {
    badge__automaticInvitation: 'Автоматты шақырулар',
    badge__automaticSuggestion: 'Автоматты ұсыныстар',
    badge__manualInvitation: 'Автоматты тіркеу жоқ',
    badge__unverified: 'Расталмаған',
    createDomainPage: {
      subtitle:
        'Расталған доменді қосыңыз. Электрондық поштасы расталған доменде тіркелген пайдаланушылар ұйымға автоматты түрде немесе сұрау арқылы қосыла алады.',
      title: 'Домен қосу',
    },
    invitePage: {
      detailsTitle__inviteFailed:
        'Шақырулар жіберілмеді. Келесі электрондық пошта мекенжайларына арналған шақырулар әлдеқада жіберілген: {{email_addresses}}.',
      formButtonPrimary__continue: 'Шақыруларды жіберу',
      selectDropdown__role: 'Рөлді таңдау',
      subtitle: 'Жаңа мүшелерді осы ұйымға шақыру',
      successMessage: 'Шақырулар сәтті жіберілді',
      title: 'Мүшелерді шақыру',
    },
    membersPage: {
      action__invite: 'Шақыру',
      action__search: undefined,
      activeMembersTab: {
        menuAction__remove: 'Мүшені жою',
        tableHeader__actions: 'Әрекеттер',
        tableHeader__joined: 'Қосылды',
        tableHeader__role: 'Рөл',
        tableHeader__user: 'Пайдаланушы',
      },
      detailsTitle__emptyRow: 'Көрсету үшін мүшелер жоқ',
      invitationsTab: {
        autoInvitations: {
          headerSubtitle:
            'Электрондық пошта доменін ұйымыңызға қосу арқылы пайдаланушыларды шақырыңыз. Сәйкес электрондық пошта доменімен тіркелген кез келген адам ұйымға кез келген уақытта қосыла алады.',
          headerTitle: 'Автоматты шақырулар',
          primaryButton: 'Расталған домендерді басқару',
        },
        table__emptyRow: 'Көрсету үшін шақырулар жоқ',
      },
      invitedMembersTab: {
        menuAction__revoke: 'Шақыруды жою',
        tableHeader__invited: 'Шақырылған',
      },
      requestsTab: {
        autoSuggestions: {
          headerSubtitle:
            'Сәйкес электрондық пошта доменімен тіркелген пайдаланушылар ұйымыңызға қосылу сұрауын көре алады',
          headerTitle: 'Автоматты ұсыныстар',
          primaryButton: 'Расталған домендерді басқару',
        },
        menuAction__approve: 'Қабылдау',
        menuAction__reject: 'Қабылдамау',
        tableHeader__requested: 'Қатысу сұрауы',
        table__emptyRow: 'Көрсету үшін сұраулар жоқ',
      },
      start: {
        headerTitle__invitations: 'Шақырулар',
        headerTitle__members: 'Мүшелер',
        headerTitle__requests: 'Сұраулар',
      },
    },
    navbar: {
      description: 'Ұйымыңызды басқару.',
      general: 'Жалпы',
      members: 'Мүшелер',
      title: 'Ұйым',
    },
    profilePage: {
      dangerSection: {
        deleteOrganization: {
          actionDescription: 'Жалғастыру үшін төмендегі өріске {{organizationName}} деп енгізіңіз.',
          messageLine1: 'Бұл ұйымды жоюға сенімдісіз бе?',
          messageLine2: 'Бұл әрекетті болдырмау мүмкін емес.',
          successMessage: 'Сіз ұйымды жойдыңыз.',
          title: 'Ұйымды жою',
        },
        leaveOrganization: {
          actionDescription: 'Жалғастыру үшін төмендегі өріске "{{organizationName}}" деп енгізіңіз.',
          messageLine1:
            'Бұл ұйымнан шығуға сенімдісіз бе? Сіз осы ұйымға және оның қолданбаларына қол жеткізе алмайсыз.',
          messageLine2: 'Бұл әрекетті болдырмау мүмкін емес.',
          successMessage: 'Сіз ұйымнан шықтыңыз.',
          title: 'Ұйымнан шығу',
        },
        title: 'Қауіп',
      },
      domainSection: {
        menuAction__manage: 'Басқару',
        menuAction__remove: 'Жою',
        menuAction__verify: 'Растау',
        primaryButton: 'Домен қосу',
        subtitle:
          'Электрондық пошта домені расталған пайдаланушылардың ұйымға автоматты түрде немесе сұрау арқылы қосылуына мүмкіндік беріңіз.',
        title: 'Расталған домендер',
      },
      successMessage: 'Ұйым жаңартылды.',
      title: 'Ұйым профилі',
    },
    removeDomainPage: {
      messageLine1: '{{domain}} электрондық пошта домені жойылды.',
      messageLine2: 'Пайдаланушылар бұдан былай ұйымға автоматты түрде қосыла алмайды',
      successMessage: '{{domain}} жойылды.',
      title: 'Доменді жою',
    },
    start: {
      headerTitle__general: 'Жалпы',
      headerTitle__members: 'Мүшелер',
      profileSection: {
        primaryButton: 'Профильді жаңарту',
        title: 'Ұйым Профилі',
        uploadAction__title: 'Логотип',
      },
    },
    verifiedDomainPage: {
      dangerTab: {
        calloutInfoLabel: 'Доменді жою шақырылған пайдаланушыларға әсер етеді.',
        removeDomainActionLabel__remove: 'Доменді жою',
        removeDomainSubtitle: 'Бұл доменді расталған домендер тізімінен жою',
        removeDomainTitle: 'Доменді жою',
      },
      enrollmentTab: {
        automaticInvitationOption__description:
          'Пайдаланушылар тіркелгеннен кейін автоматты түрде ұйымға қосылуға шақырылады және әкімшінің растауынсыз кез келген уақытта қабылдай алады',
        automaticInvitationOption__label: 'Автоматты шақырулар',
        automaticSuggestionOption__description:
          'Пайдаланушылар автоматты түрде ұйымға қосылу сұрауын алады. Қосылу үшін әкімші сұрауды растауы керек.',
        automaticSuggestionOption__label: 'Автоматты ұсыныстар',
        calloutInfoLabel: 'Қосылу әдісін өзгерту тек жаңа пайдаланушыларға әсер етеді.',
        calloutInvitationCountLabel: 'Жіберілген шақырулар: {{count}}',
        calloutSuggestionCountLabel: 'Жіберілген ұсыныстар: {{count}}',
        manualInvitationOption__description:
          'Пайдаланушылар өздігінен қосыла алмайды, оларды қолмен ғана қосуға болады.',
        manualInvitationOption__label: 'Қолмен қосу ғана',
        subtitle:
          'Осы электрондық пошта домені бар пайдаланушылардың ұйымға қосылу әдісін таңдаңыз.',
      },
      start: {
        headerTitle__danger: 'Қауіп',
        headerTitle__enrollment: 'Қосылу әдістері',
      },
      subtitle:
        '{{domain}} домені расталды. Енді осы домені бар пайдаланушылардың ұйымға қалай қосылатынын таңдаңыз.',
      title: '{{domain}} жаңарту',
    },
    verifyDomainPage: {
      formSubtitle: 'Көрсетілген электрондық поштаға жіберілген растау кодын енгізіңіз',
      formTitle: 'Растау коды',
      resendButton: 'Код алмадыңыз ба? Қайта жіберу',
      subtitle: '{{domainName}} доменін электрондық пошта арқылы растау қажет.',
      subtitleVerificationCodeScreen:
        'Растау коды {{emailAddress}} электрондық поштасына жіберілді. Жалғастыру үшін оны енгізіңіз.',
      title: 'Доменді растау',
    },
  },
  organizationSwitcher: {
    action__createOrganization: 'Ұйым құру',
    action__invitationAccept: 'Қосылу',
    action__manageOrganization: 'Баптаулар',
    action__suggestionsAccept: 'Қосылу сұрауы',
    notSelected: 'Ұйым таңдалмаған',
    personalWorkspace: 'Жеке профиль',
    suggestionsAcceptedLabel: 'Бекіту күтілуде',
  },
  paginationButton__next: 'Алға',
  paginationButton__previous: 'Артқа',
  paginationRowText__displaying: 'Көрсету',
  paginationRowText__of: 'ішінен',
  reverification: {
    alternativeMethods: {
      actionLink: 'Көмек алу',
      actionText: 'Сізде бұлардың ешқайсысы жоқ па?',
      blockButton__backupCode: 'Сақтық кодын қолдану',
      blockButton__emailCode: 'Кодты {{identifier}} жіберу',
      blockButton__passkey: undefined,
      blockButton__password: 'Құпия сөзіңізбен жалғастыру',
      blockButton__phoneCode: 'SMS кодты {{identifier}} жіберу',
      blockButton__totp: 'Аутентификация қолданбасын қолдану',
      getHelp: {
        blockButton__emailSupport: 'Қолдау қызметіне жазу',
        content:
          'Егер тіркелгіңізді растауда қиындықтар болса, бізге хабарласыңыз, және біз сізбен бірге мүмкіндігінше тез қол жеткізуге тырысамыз.',
        title: 'Көмек алу',
      },
      subtitle: 'Қиындықтар туындады ма? Растау үшін осы әдістердің кез келгенін қолдана аласыз.',
      title: 'Басқа әдісті қолдану',
    },
    backupCodeMfa: {
      subtitle: 'Сақтық коды - бұл екі факторлы аутентификацияны құрған кезде алған кодыңыз.',
      title: 'Сақтық кодын енгізіңіз',
    },
    emailCode: {
      formTitle: 'Растау коды',
      resendButton: 'Код алмадыңыз ба? Қайта жіберу',
      subtitle: '{{applicationName}} қолданбасын жалғастыру үшін',
      title: 'Электрондық поштаңызды тексеріңіз',
    },
    noAvailableMethods: {
      message: 'Растауды жалғастыру мүмкін емес. Аутентификация факторы қолжетімді емес.',
      subtitle: 'Қате орын алды',
      title: 'Тіркелгіні растау мүмкін емес',
    },
    passkey: {
      blockButton__passkey: undefined,
      subtitle: undefined,
      title: undefined,
    },
    password: {
      actionLink: 'Басқа әдісті қолдану',
      subtitle: 'Тіркелгіңізге байланысты құпия сөзді енгізіңіз',
      title: 'Құпия сөзіңізді енгізіңіз',
    },
    phoneCode: {
      formTitle: 'Растау коды',
      resendButton: 'Код алмадыңыз ба? Қайта жіберу',
      subtitle: '{{applicationName}} қолданбасын жалғастыру үшін',
      title: 'Телефоныңызды тексеріңіз',
    },
    phoneCodeMfa: {
      formTitle: 'Растау коды',
      resendButton: 'Код алмадыңыз ба? Қайта жіберу',
      subtitle: 'Жалғастыру үшін телефонға жіберілген растау кодын енгізіңіз',
      title: 'Телефоныңызды тексеріңіз',
    },
    totpMfa: {
      formTitle: 'Растау коды',
      subtitle: 'Жалғастыру үшін аутентификация қолданбасыңыздағы растау кодын енгізіңіз',
      title: 'Екі факторлы растау',
    },
  },
  signIn: {
    accountSwitcher: {
      action__addAccount: 'Тіркелгі қосу',
      action__signOutAll: 'Барлық тіркелгілерден шығу',
      subtitle: 'Жалғастыратын тіркелгіңізді таңдаңыз.',
      title: 'Тіркелгіні таңдау',
    },
    alternativeMethods: {
      actionLink: 'Көмек',
      actionText: 'Көрсетілгендердің ешқайсысы жоқ па?',
      blockButton__backupCode: 'Сақтық кодын қолдану.',
      blockButton__emailCode: 'Кодты {{identifier}} жіберу',
      blockButton__emailLink: 'Сілтемені {{identifier}} жіберу',
      blockButton__passkey: 'Кіру кілтіңізбен кіру.',
      blockButton__password: 'Құпия сөзіңізбен кіру',
      blockButton__phoneCode: 'Кодты {{identifier}} жіберу',
      blockButton__totp: 'Аутентификаторды қолдану',
      getHelp: {
        blockButton__emailSupport: 'Қолдау қызметіне жазу',
        content:
          'Егер тіркелгіңізге кіруде қиындықтар болса, бізге хабарласыңыз, және біз сізбен бірге мүмкіндігінше тез қол жеткізуге тырысамыз.',
        title: 'Көмек',
      },
      subtitle: 'Қиындықтар туындады ма? Кіру үшін осы әдістердің кез келгенін қолдана аласыз.',
      title: 'Басқа әдісті қолдану',
    },
    backupCodeMfa: {
      subtitle: '"{{applicationName}}" қолданбасын жалғастыру үшін',
      title: 'Сақтық кодын енгізіңіз',
    },
    emailCode: {
      formTitle: 'Растау коды',
      resendButton: 'Код алмадыңыз ба? Қайта жіберу.',
      subtitle: '"{{applicationName}}" қолданбасын жалғастыру үшін',
      title: 'Электрондық поштаңызды тексеріңіз',
    },
    emailLink: {
      clientMismatch: {
        subtitle:
          'Жалғастыру үшін кіруді бастаған құрылғыда және браузерде растау сілтемесін ашыңыз.',
        title: 'Растау сілтемесі осы құрылғы үшін жарамсыз.',
      },
      expired: {
        subtitle: 'Жалғастыру үшін бастапқы бетке оралыңыз.',
        title: 'Бұл растау сілтемесінің мерзімі аяқталды',
      },
      failed: {
        subtitle: 'Жалғастыру үшін бастапқы бетке оралыңыз.',
        title: 'Бұл растау сілтемесі жарамсыз.',
      },
      formSubtitle: 'Электрондық поштаңызға жіберілген растау сілтемесін қолданыңыз',
      formTitle: 'Растау сілтемесі',
      loading: {
        subtitle: 'Сіз жақында бағытталасыз',
        title: 'Кіру...',
      },
      resendButton: 'Сілтеме алмадыңыз ба? Қайта жіберу.',
      subtitle: '"{{applicationName}}" қолданбасын жалғастыру үшін',
      title: 'Электрондық поштаңызды тексеріңіз',
      unusedTab: {
        title: 'Бетті жабуға болады',
      },
      verified: {
        subtitle: 'Сіз жақында бағытталасыз',
        title: 'Сәтті кірдіңіз',
      },
      verifiedSwitchTab: {
        subtitle: 'Жалғастыру үшін бастапқы бетке оралыңыз',
        subtitleNewTab: 'Жалғастыру үшін жаңа ашылған бетке оралыңыз',
        titleNewTab: 'Басқа бетте кірдіңіз',
      },
    },
    forgotPassword: {
      formTitle: 'Құпия сөзді қалпына келтіру коды',
      resendButton: 'Кодты қайта жіберу',
      subtitle: 'Құпия сөзіңізді қалпына келтіру үшін',
      subtitle_email: 'Алдымен электрондық поштаңызға жіберілген кодты енгізіңіз.',
      subtitle_phone: 'Алдымен телефонға жіберілген кодты енгізіңіз.',
      title: 'Құпия сөзді қалпына келтіру',
    },
    forgotPasswordAlternativeMethods: {
      blockButton__resetPassword: 'Құпия сөзді қалпына келтіру',
      label__alternativeMethods: 'Немесе, басқа әдіспен кіру',
      title: 'Құпия сөзді ұмыттыңыз ба?',
    },
    noAvailableMethods: {
      message: 'Кіру мүмкін емес. Аутентификация факторы қолжетімді емес.',
      subtitle: 'Қате орын алды',
      title: 'Кіру мүмкін емес',
    },
    passkey: {
      subtitle:
        'Кіру кілтіңізді қолдану сіздің тұлғаңызды растайды. Құрылғыңыз саусақ ізіңізді, бетіңізді немесе экран құлыптауын сұрауы мүмкін.',
      title: 'Кіру кілтіңізді қолдану',
    },
    password: {
      actionLink: 'Басқа әдісті қолдану',
      subtitle: '"{{applicationName}}" қолданбасын жалғастыру үшін',
      title: 'Құпия сөзіңізді енгізіңіз',
    },
    passwordPwned: {
      title: 'Құпия сөз қауіпсіздігі бұзылған',
    },
    phoneCode: {
      formTitle: 'Растау коды',
      resendButton: 'Код алмадыңыз ба? Қайта жіберу.',
      subtitle: '"{{applicationName}}" қолданбасын жалғастыру үшін',
      title: 'Телефоныңызды тексеріңіз',
    },
    phoneCodeMfa: {
      formTitle: 'Растау коды',
      resendButton: 'Код алмадыңыз ба? Қайта жіберу.',
      subtitle: 'Жалғастыру үшін телефонға жіберілген растау кодын енгізіңіз.',
      title: 'Телефоныңызды тексеріңіз',
    },
    resetPassword: {
      formButtonPrimary: 'Құпия сөзді қалпына келтіру',
      requiredMessage: 'Қауіпсіздік мақсатында құпия сөзіңізді қалпына келтіру қажет.',
      successMessage: 'Құпия сөзіңіз сәтті өзгертілді. Кіру процесінде, күте тұрыңыз.',
      title: 'Құпия сөзді қалпына келтіру',
    },
    resetPasswordMfa: {
      detailsLabel: 'Құпия сөзді қалпына келтіру алдында тұлғаңызды растау қажет',
    },
    start: {
      actionLink: 'Тіркелу',
      actionLink__join_waitlist: undefined,
      actionLink__use_email: 'Электрондық поштаны қолдану',
      actionLink__use_email_username: 'Электрондық пошта немесе пайдаланушы атын қолдану',
      actionLink__use_passkey: 'Оның орнына кіру кілтін қолдану',
      actionLink__use_phone: 'Телефон нөмірін қолдану',
      actionLink__use_username: 'Пайдаланушы атын қолдану',
      actionText: 'Тіркелгіңіз жоқ па?',
      actionText__join_waitlist: undefined,
      subtitle: '"{{applicationName}}" қолданбасын жалғастыру үшін',
      subtitleCombined: undefined,
      title: 'Кіру',
      titleCombined: undefined,
    },
    totpMfa: {
      formTitle: 'Растау коды',
      subtitle: 'Жалғастыру үшін аутентификация қолданбасыңыздағы растау кодын енгізіңіз.',
      title: 'Екі факторлы растау',
    },
  },
  signInEnterPasswordTitle: 'Құпия сөзіңізді енгізіңіз',
  signUp: {
    continue: {
      actionLink: 'Кіру',
      actionText: 'Тіркелгіңіз бар ма?',
      subtitle: '"{{applicationName}}" қолданбасын жалғастыру үшін',
      title: 'Барлық өрістерді толтырыңыз',
    },
    emailCode: {
        formSubtitle: 'Сізге жіберілген тексеру кодын енгізіңіз',
        formTitle: 'Тексеру коды',
        resendButton: 'Кодты алмадыңыз ба? Қайта жіберу.',
        subtitle: 'құрылғыңызда жұмыс істеуді жалғастыру үшін applicationName',
        title: 'Электрондық поштаңызды тексеріңіз',
      },
      emailLink: {
        clientMismatch: {
          subtitle:
            'Жалғастыру үшін, тіркеуді бастаған құрылғы мен браузерде тексеру сілтемесін ашыңыз.',
          title: 'Бұл құрылғы үшін тексеру сілтемесі жарамсыз.',
        },
        formSubtitle: 'Сізге жіберілген тексеру сілтемесін пайдаланыңыз',
        formTitle: 'Тексеру сілтемесі',
        loading: {
          title: 'Кіру...',
        },
        resendButton: 'Сілтемені қайта жіберу',
        subtitle: 'құрылғыңызда жұмыс істеуді жалғастыру үшін applicationName',
        title: 'Электрондық поштаңызды тексеріңіз',
        verified: {
          title: 'Сәтті кіру',
        },
        verifiedSwitchTab: {
          subtitle: 'Жалғастыру үшін жаңа ашылған қойындыға қайтыңыз',
          subtitleNewTab: 'Жалғастыру үшін алдыңғы қойындыға қайтыңыз',
          title: 'Пошта тексерілді',
        },
      },
      legalConsent: {
        checkbox: {
          label__onlyPrivacyPolicy: 'Мен {{ privacyPolicyLink || link("Жеке деректерді қорғау саясаты") }} келісемін',
          label__onlyTermsOfService: 'Мен {{ termsOfServiceLink || link("Қызмет көрсету шарттары") }} келісемін',
          label__termsOfServiceAndPrivacyPolicy:
            'Мен {{ termsOfServiceLink || link("Қызмет көрсету шарттары") }} және {{ privacyPolicyLink || link("Жеке деректерді қорғау саясаты") }} келісемін',
        },
        continue: {
          subtitle: 'Қосымша оқып, қабылдаңыз, сосын жалғастырыңыз.',
          title: 'Құқықтық келісім',
        },
      },
      phoneCode: {
        formSubtitle: 'Телефоныңызға жіберілген тексеру кодын енгізіңіз',
        formTitle: 'Тексеру коды',
        resendButton: 'Кодты алмадыңыз ба? Қайта жіберу.',
        subtitle: 'құрылғыңызда жұмыс істеуді жалғастыру үшін applicationName',
        title: 'Телефон нөміріңізді тексеріңіз',
      },
      restrictedAccess: {
        actionLink: 'Кіру',
        actionText: 'Учетная запись бар ма?',
        blockButton__emailSupport: 'Қолдау қызметіне хабарласу',
        blockButton__joinWaitlist: undefined,
        subtitle:
          'Қазір тіркелу мүмкін емес. Егер сізге қол жетімділік болуы керек деп есептесеңіз, қолдау қызметімен хабарласыңыз.',
        subtitleWaitlist: undefined,
        title: 'Қол жетімділік шектелген',
      },
      start: {
        actionLink: 'Кіру',
        actionLink__use_email: 'Электрондық пошта арқылы кіру',
        actionLink__use_phone: 'Телефон арқылы кіру',
        actionText: 'Учетная запись бар ма?',
        subtitle: 'құрылғыңызда жұмыс істеуді жалғастыру үшін applicationName',
        subtitleCombined: 'құрылғыңызда жұмыс істеуді жалғастыру үшін applicationName',
        title: 'Учетную запись жасаңыз',
        titleCombined: 'Учетную запись жасаңыз',
      },
    },
    socialButtonsBlockButton: '{{provider|titleize}} арқылы жалғастыру',
socialButtonsBlockButtonManyInView: '{{provider|titleize}}',
unstable__errors: {
  already_a_member_in_organization: '{{email}} ұйымның мүшесі болып табылады.',
  captcha_invalid:
    'Тіркеу қауіпсіздік тексерістері сәтсіз аяқталғандықтан жүзеге аспады. Қайта көру үшін бетті жаңартыңыз немесе қосымша көмек алу үшін қолдау қызметіне хабарласыңыз.',
  captcha_unavailable:
    'Ботты тексеру сәтсіз аяқталғандықтан тіркеу орындалмады. Қайта көру үшін бетті жаңартыңыз немесе қосымша көмек алу үшін қолдау қызметіне хабарласыңыз.',
  form_code_incorrect: undefined,
  form_identifier_exists__email_address: 'Бұл электрондық пошта мекенжайы бос емес. Басқасын көріңіз.',
  form_identifier_exists__phone_number: 'Бұл телефон нөмірі бос емес. Басқасын көріңіз.',
  form_identifier_exists__username: 'Бұл пайдаланушы аты бос емес. Басқасын көріңіз.',
  form_identifier_not_found: undefined,
  form_param_format_invalid: undefined,
  form_param_format_invalid__email_address: 'Электрондық пошта мекенжайы дұрыс болуы керек.',
  form_param_format_invalid__phone_number: 'Телефон нөмірі халықаралық дұрыс форматта болуы керек.',
  form_param_max_length_exceeded__first_name: 'Атыңыз 256 таңбадан аспауы керек.',
  form_param_max_length_exceeded__last_name: 'Тегіңіз 256 таңбадан аспауы керек.',
  form_param_max_length_exceeded__name: 'Аты 256 таңбадан аспауы керек.',
  form_param_nil: undefined,
  form_param_value_invalid: undefined,
  form_password_incorrect: undefined,
  form_password_length_too_short: undefined,
  form_password_not_strong_enough: 'Құпия сөзіңіз жеткілікті сенімді емес.',
  form_password_pwned: 'Бұл құпия сөз бұзылған және қолдануға болмайды, басқасын таңдаңыз.',
  form_password_pwned__sign_in: 'Бұл құпия сөз деректердің ағып кетуінен табылды. Құпия сөзіңізді қалпына келтіріңіз.',
  form_password_size_in_bytes_exceeded:
    'Құпия сөзіңіз рұқсат етілген байт санынан асып кетті, қысқартыңыз немесе арнайы таңбаларды алып тастаңыз.',
  form_password_validation_failed: 'Құпия сөз қате',
  form_username_invalid_character: undefined,
  form_username_invalid_length: undefined,
  identification_deletion_failed: 'Соңғы идентификацияны жою мүмкін емес.',
  not_allowed_access: undefined,
  organization_domain_blocked: 'Бұл пошта провайдерінің домені бұғатталған. Басқасын қолданыңыз.',
  organization_domain_common: 'Бұл жиі қолданылатын пошта домені. Басқасын қолданыңыз.',
  organization_domain_exists_for_enterprise_connection: undefined,
  organization_membership_quota_exceeded:
    'Сіз ұйымдарға мүшелік шегіне жеттіңіз, шақыруларды қоса алғанда.',
  organization_minimum_permissions_needed:
    'Ұйымда ең аз рұқсаттары бар кем дегенде бір мүше болуы керек.',
  passkey_already_exists: 'Бұл құрылғыда қолжеткізу кілті тіркелген.',
  passkey_not_supported: 'Бұл құрылғыда қолжеткізу кілттері қолдау таппайды.',
  passkey_pa_not_supported: 'Тіркелу үшін платформалық аутентификатор қажет, бірақ құрылғы оны қолдамайды.',
  passkey_registration_cancelled: 'Қолжеткізу кілтін тіркеу жойылды немесе уақыт аяқталды.',
  passkey_retrieval_cancelled: 'Қолжеткізу кілтін тексеру жойылды немесе уақыт аяқталды.',
  passwordComplexity: {
    maximumLength: '{{length}} таңбадан кем',
    minimumLength: '{{length}} немесе одан көп таңба',
    requireLowercase: 'кіші әріп',
    requireNumbers: 'сан',
    requireSpecialCharacter: 'арнайы таңба',
    requireUppercase: 'үлкен әріп',
    sentencePrefix: 'Құпия сөзіңіз мыналарды қамтуы керек:',
  },
  phone_number_exists: 'Бұл телефон нөмірі бос емес. Басқасын көріңіз.',
  web3_missing_identifier: undefined,
  zxcvbn: {
    couldBeStronger: 'Құпия сөзіңіз жарамды, бірақ оны күшейтуге болады. Көбірек таңба қосыңыз.',
    goodPassword: 'Жақсы жұмыс. Бұл өте сенімді құпия сөз.',
    notEnough: 'Құпия сөзіңіз жеткілікті сенімді емес.',
    suggestions: {
      allUppercase: 'Барлық әріптерді бас әріппен жазбаңыз.',
      anotherWord: 'Көп қолданылмайтын сөздер қосыңыз.',
      associatedYears: 'Сізбен байланысты жылдардан аулақ болыңыз.',
      capitalization: 'Тек бірінші әріпті бас әріппен жазбаңыз.',
      dates: 'Сізге қатысты даталар мен жылдардан аулақ болыңыз.',
      l33t: '«@» орнына «a» сияқты болжамды алмастырулардан аулақ болыңыз.',
      longerKeyboardPattern: 'Ұзақ пернетақта үлгілерін қолданыңыз және бағытты бірнеше рет өзгертіңіз.',
      noNeed: 'Символдар, сандар немесе бас әріптерсіз де сенімді құпия сөз жасауға болады.',
      pwned: 'Егер бұл құпия сөзді басқа жерде қолдансаңыз, оны ауыстыру керек.',
      recentYears: 'Соңғы жылдардан аулақ болыңыз.',
      repeated: 'Қайталанатын сөздер мен таңбалардан аулақ болыңыз.',
      reverseWords: 'Жиі қолданылатын сөздерді кері жазудан аулақ болыңыз.',
      sequences: 'Жиі кездесетін таңбалар тізбектерінен аулақ болыңыз.',
      useWords: 'Бірнеше сөз қолданыңыз, бірақ жиі кездесетін тіркестерден аулақ болыңыз.',
    },warnings: {
        common: 'Бұл жиі қолданылатын құпия сөз.',
        commonNames: 'Жиі кездесетін есімдер мен тегілерді болжау оңай.',
        dates: 'Күндерді болжау оңай.',
        extendedRepeat: '"abcabcabc" сияқты қайталанатын әріптер үлгілерін болжау оңай.',
        keyPattern: 'Перне тақтасының қысқа үлгілерін болжау оңай.',
        namesByThemselves: 'Жеке есімдерді немесе тегтерді болжау оңай.',
        pwned: 'Сіздің құпия сөзіңіз Интернеттегі деректердің құпиялылығының бұзылуы кезінде ашылған.',
        recentYears: 'Соңғы жылдарды болжау оңай.',
        sequences: '"abc" сияқты жиі кездесетін әріптер тізбегін болжау оңай.',
        similarToCommon: 'Бұл құпия сөз жиі қолданылатын құпия сөзге ұқсас.',
        simpleRepeat: '"aaa" сияқты қайталанатын әріптерді болжау оңай.',
        straightRow: 'Перне тақтасындағы түзу қатарларды болжау оңай.',
        topHundred: 'Бұл жиі қолданылатын құпия сөз.',
        topTen: 'Бұл өте жиі қолданылатын құпия сөз.',
        userInputs: 'Жеке деректер немесе бетке қатысты деректер болмауы керек.',
        wordByItself: 'Жеке сөздерді болжау оңай.',
      },
      },
      },
      userButton: {
      action__addAccount: 'Есептік жазбаны қосу',
      action__manageAccount: 'Есептік жазбаны басқару',
      action__signOut: 'Шығу',
      action__signOutAll: 'Барлық есептік жазбалардан шығу',
      },
      userProfile: {
      __experimental_billingPage: {
        start: {
          headerTitle__invoices: undefined,
          headerTitle__paymentSources: undefined,
          headerTitle__plans: undefined,
        },
        title: undefined,
      },
      backupCodePage: {
        actionLabel__copied: 'Көшірілді!',
        actionLabel__copy: 'Барлығын көшіру',
        actionLabel__download: '.txt жүктеу',
        actionLabel__print: 'Басып шығару',
        infoText1: 'Бұл есептік жазба үшін резервтік кодтар қосылады.',
        infoText2:
          'Резервтік кодтарды құпия ұстаңыз және оларды қауіпсіз жерде сақтаңыз. Егер олардың қауіпсіздігі қамтамасыз етілмеген деп күмәндансаңыз, жаңа резервтік кодтар жасай аласыз.',
        subtitle__codelist: 'Оларды қауіпсіз сақтаңыз және ешкімге айтпаңыз.',
        successMessage:
          'Резервтік кодтар қосылды. Аутентификация құрылғысына қол жеткізе алмасаңыз, есептік жазбаңызға кіру үшін осы кодтардың бірін пайдалана аласыз. Әр код тек бір рет қолданылады.',
        successSubtitle:
          'Аутентификация құрылғысына қол жеткізе алмасаңыз, есептік жазбаңызға кіру үшін осы кодтардың бірін пайдалана аласыз.',
        title: 'Резервтік растау кодын қосу',
        title__codelist: 'Резервтік кодтар',
      },
      connectedAccountPage: {
        formHint: 'Есептік жазбаңызды қосу үшін провайдерді таңдаңыз.',
        formHint__noAccounts: 'Қолжетімді сыртқы есептік жазба провайдерлері жоқ.',
        removeResource: {
          messageLine1: '{{identifier}} сіздің есептік жазбаңыздан өшіріледі.',
          messageLine2:
            'Сіз бұл қосылған есептік жазбаны пайдалана алмайсыз және кез келген тәуелді функциялар жұмыс істемейді.',
          successMessage: '{{connectedAccount}} сіздің есептік жазбаңыздан өшірілді.',
          title: 'Қосылған есептік жазбаны өшіру',
        },
        socialButtonsBlockButton: '{{provider|titleize}} есептік жазбасын қосу',
        successMessage: 'Провайдер сіздің есептік жазбаңызға қосылды',
        title: 'Қосылған есептік жазбаны қосу',
      },
      deletePage: {
        actionDescription: 'Жалғастыру үшін төменде "Есептік жазбаны өшіру" деп енгізіңіз.',
        confirm: 'Есептік жазбаны өшіру',
        messageLine1: 'Есептік жазбаңызды өшіргіңіз келетініне сенімдісіз бе?',
        messageLine2: 'Бұл әрекет қайтымсыз және ол қалпына келтірілмейді.',
        title: 'Есептік жазбаны өшіру',
      },
      emailAddressPage: {
        emailCode: {
          formHint: 'Бұл электрондық пошта мекенжайына растау коды жіберілетін болады.',
          formSubtitle: '{{identifier}} жіберілген растау кодты енгізіңіз',
          formTitle: 'Растау коды',
          resendButton: 'Код алмадыңыз ба? Қайта жіберу',
          successMessage: '{{identifier}} электрондық поштасы сіздің есептік жазбаңызға қосылды.',
        },
        emailLink: {
          formHint: 'Бұл электрондық пошта мекенжайына растау сілтемесі жіберілетін болады.',
          formSubtitle: '{{identifier}} жіберілген электрондық поштадағы растау сілтемесін басыңыз',
          formTitle: 'Растау сілтемесі',
          resendButton: 'Сілтемені қайта жіберу',
          successMessage: '{{identifier}} электрондық поштасы сіздің есептік жазбаңызға қосылды.',
        },
        enterpriseSSOLink: {
          formButton: undefined,
          formSubtitle: undefined,
        },
        formHint: undefined,
        removeResource: {
          messageLine1: '{{identifier}} осы есептік жазбадан өшіріледі.',
          messageLine2: 'Сіз бұл электрондық пошта мекенжайы арқылы кіре алмайсыз.',
          successMessage: '{{emailAddress}} сіздің есептік жазбаңыздан өшірілді.',
          title: 'Электрондық пошта мекенжайын өшіру',
        },
        title: 'Электрондық пошта мекенжайын қосу',
        verifyTitle: 'Электрондық поштаны растау',
      },
      formButtonPrimary__add: 'Қосу',
      formButtonPrimary__continue: 'Жалғастыру',
      formButtonPrimary__finish: 'Аяқтау',
      formButtonPrimary__remove: 'Өшіру',
      formButtonPrimary__save: 'Сақтау',
      formButtonReset: 'Болдырмау',
      mfaPage: {
        formHint: 'Қосу үшін әдісті таңдаңыз.',
        title: 'Екі факторлы аутентификацияны қосу',
      },
      mfaPhoneCodePage: {
        backButton: 'Бар телефон нөмірін қолдану',
        primaryButton__addPhoneNumber: 'Телефон нөмірін қосу',
        removeResource: {
          messageLine1: '{{identifier}} кіру кезінде растау кодтарын ала алмайтын болады.',
          messageLine2: 'Есептік жазбаңыздың қауіпсіздігі төмендеуі мүмкін. Жалғастырғыңыз келетініне сенімдісіз бе?',
          successMessage: 'SMS коды арқылы екі факторлы аутентификация {{mfaPhoneCode}} үшін өшірілді',
          title: 'Екі факторлы аутентификацияны өшіру',
        },
        subtitle__availablePhoneNumbers:
          'SMS коды арқылы екі факторлы аутентификацияға тіркелу үшін телефон нөмірін таңдаңыз.',
        subtitle__unavailablePhoneNumbers:
          'SMS коды арқылы екі факторлы аутентификацияға тіркелу үшін қолжетімді телефон нөмірлері жоқ. Жаңа телефон нөмірін қосыңыз.',
        successMessage1:
          'Кіру кезінде осы телефон нөміріне жіберілетін растау кодын енгізу қажет болады.',
        successMessage2:
          'Осы резервтік кодтарды сақтап, қауіпсіз жерде сақтаңыз. Егер аутентификация құрылғысына қол жеткізе алмасаңыз, кіру үшін резервтік кодтарды пайдалана аласыз.',
        successTitle: 'SMS коды арқылы растау қосылды',
        title: 'SMS коды арқылы тексеруді қосу',
      },
      mfaTOTPPage: {
        authenticatorApp: {
          buttonAbleToScan__nonPrimary: 'Оның орнына QR кодын сканерлеу',
          buttonUnableToScan__nonPrimary: 'QR кодын сканерлей алмайсыз ба?',
          infoText__ableToScan:
            'Аутентификация қолданбаңызда жаңа кіру әдісін орнатыңыз және оны есептік жазбаңызға байланыстыру үшін келесі QR кодын сканерлеңіз.',
          infoText__unableToScan:
            'Аутентификация қолданбаңызда жаңа кіру әдісін орнатыңыз және төменде көрсетілген кілтті енгізіңіз.',
          inputLabel__unableToScan1:
            'Уақытқа не бір реттік құпия сөздер қосылғанына көз жеткізіп, есептік жазбаңызды байланыстыруды аяқтаңыз.',
          inputLabel__unableToScan2:
            'Сонымен қатар, егер аутентификация қолданбаңыз TOTP URI қолдаса, толық URI мекенжайын да көшіре аласыз.',
        },
        removeResource: {
          messageLine1:
            'Осы аутентификация қолданбасынан растау кодтары кіру кезінде қажет болмайтын болады.',
          messageLine2: 'Есептік жазбаңыздың қауіпсіздігі төмендеуі мүмкін. Жалғастырғыңыз келетініне сенімдісіз бе?',
          successMessage: 'Аутентификация қолданбасы арқылы екі факторлы аутентификация өшірілді.',
          title: 'Екі факторлы аутентификацияны өшіру',
        },
        successMessage:
          'Екі факторлы аутентификация қосылды. Кіру кезінде осы аутентификация қолданбасынан растау кодын енгізу қажет болады.',
        title: 'Аутентификация қолданбасын қосу',
        verifySubtitle: 'Аутентификация қолданбаңыз жасаған растау кодын енгізіңіз',
        verifyTitle: 'Растау коды',
      },
      mobileButton__menu: 'Мәзір',
      navbar: {
        account: 'Есептік жазба',
        billing: undefined,
        description: 'Есептік жазба ақпаратын басқару.',
        security: 'Қауіпсіздік',
        title: 'Есептік жазба',
      },
      passkeyScreen: {
        removeResource: {
          messageLine1: '{{name}} осы есептік жазбадан өшіріледі.',
          title: 'Пасскейді өшіру',
        },
        subtitle__rename: 'Пасскейді оңай табу үшін оның атауын өзгерте аласыз.',
        title__rename: 'Пасскейдің атауын өзгерту',
      },
      passwordPage: {
        checkboxInfoText__signOutOfOtherSessions:
          'Ескі құпия сөзді пайдаланған барлық басқа құрылғылардан шығу ұсынылады.',
        readonly: 'Қазіргі уақытта құпия сөзді өңдеу мүмкін емес, өйткені сіз тек корпоративтік байланыс арқылы кіре аласыз.',
        successMessage__set: 'Құпия сөзіңіз орнатылды.',
        successMessage__signOutOfOtherSessions: 'Барлық басқа құрылғылардан шығарылды.',
        successMessage__update: 'Құпия сөзіңіз жаңартылды.',
        title__set: 'Құпия сөзді орнату',
        title__update: 'Құпия сөзді өзгерту',
      },
      phoneNumberPage: {
        infoText: 'Бұл телефон нөміріне растау сілтемесі жіберілетін болады. Хабарлама және деректер тарифтері қолданылуы мүмкін.',
        removeResource: {
          messageLine1: '{{identifier}} осы есептік жазбадан өшіріледі.',
          messageLine2: 'Сіз бұл телефон нөмірі арқылы кіре алмайсыз.',
          successMessage: '{{phoneNumber}} сіздің есептік жазбаңыздан өшірілді.',
          title: 'Телефон нөмірін өшіру',
        },
        successMessage: '{{identifier}} сіздің есептік жазбаңызға қосылды.',
        title: 'Телефон нөмірін қосу',
        verifySubtitle: '{{identifier}} жіберілген растау кодты енгізіңіз',
        verifyTitle: 'Телефон нөмірін растау',
      },
      profilePage: {
        fileDropAreaHint: 'JPG, PNG, GIF немесе WEBP форматындағы 10 МБ-тан кіші кескін жүктеңіз',
        imageFormDestructiveActionSubtitle: 'Кескінді өшіру',
        imageFormSubtitle: 'Кескін жүктеу',
        imageFormTitle: 'Профиль кескіні',
        readonly: 'Профиль ақпараты корпоративтік байланыс арқылы берілген және оны өңдеу мүмкін емес.',
        successMessage: 'Профиліңіз жаңартылды.',
        title: 'Профильді жаңарту',
      },
      start: {
        activeDevicesSection: {
          destructiveAction: 'Құрылғыдан шығу',
          title: 'Белсенді құрылғылар',
        },
        connectedAccountsSection: {
          actionLabel__connectionFailed: 'Қайтадан көру',
          actionLabel__reauthorize: 'Қазір авторизациялау',
          destructiveActionTitle: 'Өшіру',
          primaryButton: 'Есептік жазбаны қосу',
          subtitle__disconnected: 'Бұл есептік жазба ажыратылды.',
          subtitle__reauthorize:
            'Қажетті рұқсаттар жаңартылды және сіз шектелген функционалдылықпен беттесе аласыз. Мүмкін мәселелерді болдырмау үшін қолданбаны қайта авторизациялаңыз',
          title: 'Қосылған есептік жазбалар',
        },
        dangerSection: {
          deleteAccountButton: 'Есептік жазбаны өшіру',
          title: 'Есептік жазбаны өшіру',
        },
        emailAddressesSection: {
          destructiveAction: 'Электрондық поштаны өшіру',
          detailsAction__nonPrimary: 'Негізгі ретінде орнату',
          detailsAction__primary: 'Растауды аяқтау',
          detailsAction__unverified: 'Растау',
          primaryButton: 'Электрондық пошта мекенжайын қосу',
          title: 'Электрондық пошта мекенжайлары',
        },
        enterpriseAccountsSection: {
          title: 'Корпоративтік есептік жазбалар',
        },
        headerTitle__account: 'Есептік жазба',
        headerTitle__security: 'Қауіпсіздік',
        mfaSection: {
          backupCodes: {
            actionLabel__regenerate: 'Кодтарды қайта жасау',
            headerTitle: 'Резервтік кодтар',
            subtitle__regenerate:
              'Жаңа қауіпсіз резервтік кодтар жиынтығын алыңыз. Алдыңғы резервтік кодтар өшіріледі және пайдаланыла алмайды.',
            title__regenerate: 'Жаңа резервтік кодтарды жасау',
          },
          phoneCode: {
            actionLabel__setDefault: 'Әдепкі ретінде орнату',
            destructiveActionLabel: 'Телефон нөмірін өшіру',
          },
          primaryButton: 'Екі факторлы аутентификацияны қосу',
          title: 'Екі факторлы аутентификация',
          totp: {
            destructiveActionTitle: 'Өшіру',
            headerTitle: 'Аутентификация қолданбасы',
          },
        },
        passkeysSection: {
          menuAction__destructive: 'Өшіру',
          menuAction__rename: 'Атауын өзгерту',
          primaryButton: undefined,
          title: 'Пасскейдер',
        },
        passwordSection: {
          primaryButton__setPassword: 'Құпия сөзді орнату',
          primaryButton__updatePassword: 'Құпия сөзді өзгерту',
          title: 'Құпия сөз',
        },
        phoneNumbersSection: {
          destructiveAction: 'Телефон нөмірін өшіру',
          detailsAction__nonPrimary: 'Негізгі ретінде орнату',
          detailsAction__primary: 'Растауды аяқтау',
          detailsAction__unverified: 'Растауды аяқтау',
          primaryButton: 'Телефон нөмірін қосу',
          title: 'Телефон нөмірлері',
        },
        profileSection: {
          primaryButton: 'Профильді жаңарту',
          title: 'Профиль',
        },
        usernameSection: {
          primaryButton__setUsername: 'Пайдаланушы атын орнату',
          primaryButton__updateUsername: 'Пайдаланушы атын өзгерту',
          title: 'Пайдаланушы аты',
        },
        web3WalletsSection: {
          destructiveAction: 'Әмиянды өшіру',
          detailsAction__nonPrimary: undefined,
          primaryButton: 'Web3 әмияндары',
          title: 'Web3 әмияндары',
        },
      },
      usernamePage: {
        successMessage: 'Пайдаланушы атыңыз жаңартылды.',
        title__set: 'Пайдаланушы атын жаңарту',
        title__update: 'Пайдаланушы атын жаңарту',
      },
      web3WalletPage: {
        removeResource: {
          messageLine1: '{{identifier}} осы есептік жазбадан өшіріледі.',
          messageLine2: 'Сіз бұл web3 әмияны арқылы кіре алмайсыз.',
          successMessage: '{{web3Wallet}} сіздің есептік жазбаңыздан өшірілді.',
          title: 'Web3 әмиянын өшіру',
        },
        subtitle__availableWallets: 'Есептік жазбаңызға қосу үшін web3 әмиянын таңдаңыз.',
        subtitle__unavailableWallets: 'Қолжетімді web3 әмияндары жоқ.',
        successMessage: 'Әмиян сіздің есептік жазбаңызға қосылды.',
        title: 'Web3 әмиянын қосу',
        web3WalletButtonsBlockButton: '{{provider|titleize}}',
      },
      },
      waitlist: {
      start: {
        actionLink: undefined,
        actionText: undefined,
        formButton: undefined,
        subtitle: undefined,
        title: undefined,
      },
      success: {
        message: undefined,
        subtitle: undefined,
        title: undefined,
      },
      }
    }