import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';
import { ToastProvider } from '@/providers/toast-provider';
import { ConfettiProvider } from '@/providers/confetti-provider';
import { localization } from '@/localization/kz';
const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'Ustaz Okytu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={localization}
    afterSignInUrl=''>
      <html lang="kk"> {/* Set the HTML language attribute to Kazakh */}
        <body className={inter.className}>
          <ConfettiProvider />
          <ToastProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
